services:
  catalog.db:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres.catalog:/var/lib/postgresql/data/


  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__Database=Server=catalog.db;Port=5432;Database=catalogDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalog.db
    ports:
      - "6060:8080"